#model: openrouter/anthropic/claude-haiku-4.5
#editor-model: openrouter/anthropic/claude-haiku-4.5
#weak-model: openrouter/anthropic/claude-haiku-4.5

model: openrouter/deepseek/deepseek-v3.2
weak-model: openrouter/deepseek/deepseek-v3.2

map-tokens: 4096

auto-commits: false
dirty-commits: false
attribute-author: true
attribute-committer: true

git: true
gitignore: false

dark-mode: true
pretty: true

stream: true

read: AGENTS_SUMMARY.md

chat-language: english
commit-language: english

cache-prompts: true
cache-keepalive-pings: 3
notifications: true
