version: "1.0"
networks:
  default:
    driver: bridge
    subnet: auto

volumes:
:
    size: 20G
  app_data:
    size: 10G

vms:
  fedora-vm:
    image: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2
    cpu: 2
    memory: 2048
    disk:
      size: 8G
    networks:
      - default
    volumes:
      - app_data:/var/lib/app

  ubuntu-vm:
    image: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
    cpu: 2
    memory: 2048
    networks:
      - default
    volumes:
      - ./scripts:/opt/scripts

  database-vm:
    image: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
    cpu: 4
    memory: 4096
    disk:
      size: 20G
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - app_data:/mnt/shared:ro
      - /host/absolute/path:/mnt/host
